spring.application.name=hubops

spring.datasource.url=jdbc:mysql://localhost:3306/hubopsdb
spring.datasource.username=root
spring.datasource.password=Lion3938@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080